# Generated by Django 6.0.5 on 2026-05-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='URL externe (Cloudinary, etc.) — utilisée si aucune image locale'),
        ),
    ]
