# Generated by Django 6.0.5 on 2026-05-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='report_pdf',
            field=models.FileField(blank=True, help_text='Rapport PDF du projet', null=True, upload_to='projects/reports/'),
        ),
    ]
